[2024-10-01T00:43:54.929-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-01T00:43:54.938-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-10-01T03:43:52.198621+00:00 [queued]>
[2024-10-01T00:43:54.944-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-10-01T03:43:52.198621+00:00 [queued]>
[2024-10-01T00:43:54.945-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-01T00:43:54.963-0300] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): elt_documento_pagar_spark> on 2024-10-01 03:43:52.198621+00:00
[2024-10-01T00:43:54.967-0300] {standard_task_runner.py:72} INFO - Started process 8654 to run task
[2024-10-01T00:43:54.973-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'elt_documento_pagar_spark', 'manual__2024-10-01T03:43:52.198621+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp0olcdow_']
[2024-10-01T00:43:54.976-0300] {standard_task_runner.py:105} INFO - Job 111: Subtask elt_documento_pagar_spark
[2024-10-01T00:43:55.014-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-10-01T03:43:52.198621+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-10-01T00:43:55.078-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='elt_documento_pagar_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:43:52.198621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T03:43:52.198621+00:00'
[2024-10-01T00:43:55.079-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-01T00:43:55.092-0300] {base.py:84} INFO - Retrieving connection 'spark'
[2024-10-01T00:43:55.093-0300] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 8g --name arrow-spark --deploy-mode client ./dags/sparkjob.py 2024-10-01 sqlserver://127.0.0.1:1433;databaseName=Teste
[2024-10-01T00:43:56.514-0300] {spark_submit.py:579} INFO - 24/10/01 00:43:56 WARN Utils: Your hostname, DESKTOP-PEJJLJO resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2024-10-01T00:43:56.516-0300] {spark_submit.py:579} INFO - 24/10/01 00:43:56 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-10-01T00:43:56.879-0300] {spark_submit.py:579} INFO - python3: can't open file '/home/gabzarp/airflow/dags/sparkjob.py': [Errno 2] No such file or directory
[2024-10-01T00:43:56.895-0300] {spark_submit.py:579} INFO - 24/10/01 00:43:56 INFO ShutdownHookManager: Shutdown hook called
[2024-10-01T00:43:56.896-0300] {spark_submit.py:579} INFO - 24/10/01 00:43:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-f178d62c-a893-458c-9739-40e1d48f4b98
[2024-10-01T00:43:56.932-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 8g --name arrow-spark --deploy-mode client ./dags/sparkjob.py 2024-10-01 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 2.
[2024-10-01T00:43:56.935-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=elt_documento_pagar_spark, run_id=manual__2024-10-01T03:43:52.198621+00:00, execution_date=20241001T034352, start_date=20241001T034354, end_date=20241001T034356
[2024-10-01T00:43:56.947-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-01T00:43:56.948-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 111 for task elt_documento_pagar_spark (Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 8g --name arrow-spark --deploy-mode client ./dags/sparkjob.py 2024-10-01 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 2.; 8654)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://127.0.0.1:7077 --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --total-executor-cores 3 --executor-memory 8g --name arrow-spark --deploy-mode client ./dags/sparkjob.py 2024-10-01 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 2.
[2024-10-01T00:43:56.993-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-01T00:43:57.001-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T00:43:57.001-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
