[2024-09-13T00:33:24.503-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T00:33:24.512-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T03:33:21.167118+00:00 [queued]>
[2024-09-13T00:33:24.517-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T03:33:21.167118+00:00 [queued]>
[2024-09-13T00:33:24.517-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T00:33:24.534-0300] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): elt_documento_pagar_spark> on 2024-09-13 03:33:21.167118+00:00
[2024-09-13T00:33:24.538-0300] {standard_task_runner.py:72} INFO - Started process 29421 to run task
[2024-09-13T00:33:24.540-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'elt_documento_pagar_spark', 'manual__2024-09-13T03:33:21.167118+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmp3olhwpy0']
[2024-09-13T00:33:24.542-0300] {standard_task_runner.py:105} INFO - Job 59: Subtask elt_documento_pagar_spark
[2024-09-13T00:33:24.571-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T03:33:21.167118+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-13T00:33:24.858-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='elt_documento_pagar_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T03:33:21.167118+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T03:33:21.167118+00:00'
[2024-09-13T00:33:24.859-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T00:33:24.880-0300] {spark_submit.py:273} INFO - Could not load connection string spark, defaulting to yarn
[2024-09-13T00:33:24.882-0300] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.mongodb.input.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.mongodb.output.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8 --total-executor-cores 3 --executor-memory 30g --name arrow-spark ./dags/sparkjob.py 2024-09-13 sqlserver://127.0.0.1:1433;databaseName=Teste
[2024-09-13T00:33:27.883-0300] {spark_submit.py:579} INFO - 24/09/13 00:33:27 WARN Utils: Your hostname, DESKTOP-PEJJLJO resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2024-09-13T00:33:27.885-0300] {spark_submit.py:579} INFO - 24/09/13 00:33:27 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-09-13T00:33:27.955-0300] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-09-13T00:33:27.955-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-09-13T00:33:27.956-0300] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-09-13T00:33:27.984-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.mongodb.input.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.mongodb.output.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8 --total-executor-cores 3 --executor-memory 30g --name arrow-spark ./dags/sparkjob.py 2024-09-13 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 1.
[2024-09-13T00:33:27.990-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=elt_documento_pagar_spark, run_id=manual__2024-09-13T03:33:21.167118+00:00, execution_date=20240913T033321, start_date=20240913T033324, end_date=20240913T033327
[2024-09-13T00:33:28.023-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T00:33:28.023-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task elt_documento_pagar_spark (Cannot execute: spark-submit --master yarn --conf spark.mongodb.input.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.mongodb.output.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8 --total-executor-cores 3 --executor-memory 30g --name arrow-spark ./dags/sparkjob.py 2024-09-13 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 1.; 29421)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.mongodb.input.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.mongodb.output.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8 --total-executor-cores 3 --executor-memory 30g --name arrow-spark ./dags/sparkjob.py 2024-09-13 sqlserver://127.0.0.1:1433;databaseName=Teste. Error code is: 1.
[2024-09-13T00:33:28.046-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-13T00:33:28.058-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T00:33:28.064-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
