[2024-09-13T01:42:11.196-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T01:42:11.203-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T04:41:43.125671+00:00 [queued]>
[2024-09-13T01:42:11.207-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T04:41:43.125671+00:00 [queued]>
[2024-09-13T01:42:11.207-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T01:42:11.220-0300] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): elt_documento_pagar_spark> on 2024-09-13 04:41:43.125671+00:00
[2024-09-13T01:42:11.223-0300] {standard_task_runner.py:72} INFO - Started process 84537 to run task
[2024-09-13T01:42:11.225-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'elt_documento_pagar_spark', 'manual__2024-09-13T04:41:43.125671+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpwelbob5p']
[2024-09-13T01:42:11.226-0300] {standard_task_runner.py:105} INFO - Job 77: Subtask elt_documento_pagar_spark
[2024-09-13T01:42:11.255-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.elt_documento_pagar_spark manual__2024-09-13T04:41:43.125671+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-13T01:42:11.304-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='elt_documento_pagar_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T04:41:43.125671+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T04:41:43.125671+00:00'
[2024-09-13T01:42:11.305-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T01:42:11.327-0300] {base.py:84} INFO - Retrieving connection 'spark'
[2024-09-13T01:42:11.328-0300] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://127.0.0.1:7077 --conf spark.mongodb.input.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.mongodb.output.uri=mongodb://127.0.0.1:27017/Financeiro --conf spark.network.timeout=10000000 --conf spark.executor.heartbeatInterval=10000000 --conf spark.storage.blockManagerSlaveTimeoutMs=10000000 --conf spark.driver.maxResultSize=20g --packages org.mongodb.spark:mongo-spark-connector_2.12:3.0.0,com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8 --total-executor-cores 3 --executor-memory 30g --name arrow-spark --deploy-mode client ./dags/sparkjob.py 2024-09-13 sqlserver://127.0.0.1:1433;databaseName=Teste
[2024-09-13T01:42:13.411-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:13 WARN Utils: Your hostname, DESKTOP-PEJJLJO resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2024-09-13T01:42:13.413-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:13 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-09-13T01:42:13.631-0300] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/gabzarp/.local/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-09-13T01:42:13.750-0300] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/gabzarp/.ivy2/cache
[2024-09-13T01:42:13.751-0300] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/gabzarp/.ivy2/jars
[2024-09-13T01:42:13.755-0300] {spark_submit.py:579} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2024-09-13T01:42:13.755-0300] {spark_submit.py:579} INFO - com.microsoft.sqlserver#mssql-jdbc added as a dependency
[2024-09-13T01:42:13.756-0300] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-46517288-d57d-4c86-acb7-2f9bdbb30695;1.0
[2024-09-13T01:42:13.756-0300] {spark_submit.py:579} INFO - confs: [default]
[2024-09-13T01:42:13.881-0300] {spark_submit.py:579} INFO - found org.mongodb.spark#mongo-spark-connector_2.12;3.0.0 in central
[2024-09-13T01:42:13.904-0300] {spark_submit.py:579} INFO - found org.mongodb#mongodb-driver-sync;4.0.5 in central
[2024-09-13T01:42:13.923-0300] {spark_submit.py:579} INFO - found org.mongodb#bson;4.0.5 in central
[2024-09-13T01:42:13.942-0300] {spark_submit.py:579} INFO - found org.mongodb#mongodb-driver-core;4.0.5 in central
[2024-09-13T01:42:13.963-0300] {spark_submit.py:579} INFO - found com.microsoft.sqlserver#mssql-jdbc;8.4.1.jre8 in central
[2024-09-13T01:42:13.979-0300] {spark_submit.py:579} INFO - :: resolution report :: resolve 217ms :: artifacts dl 6ms
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - :: modules in use:
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - com.microsoft.sqlserver#mssql-jdbc;8.4.1.jre8 from central in [default]
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - org.mongodb#bson;4.0.5 from central in [default]
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - org.mongodb#mongodb-driver-core;4.0.5 from central in [default]
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - org.mongodb#mongodb-driver-sync;4.0.5 from central in [default]
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - org.mongodb.spark#mongo-spark-connector_2.12;3.0.0 from central in [default]
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-13T01:42:13.980-0300] {spark_submit.py:579} INFO - |      default     |   5   |   0   |   0   |   0   ||   5   |   0   |
[2024-09-13T01:42:13.981-0300] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-13T01:42:13.985-0300] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-46517288-d57d-4c86-acb7-2f9bdbb30695
[2024-09-13T01:42:13.986-0300] {spark_submit.py:579} INFO - confs: [default]
[2024-09-13T01:42:13.991-0300] {spark_submit.py:579} INFO - 0 artifacts copied, 5 already retrieved (0kB/6ms)
[2024-09-13T01:42:14.230-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-13T01:42:15.142-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkContext: Running Spark version 3.5.2
[2024-09-13T01:42:15.142-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-13T01:42:15.142-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkContext: Java version 11.0.24
[2024-09-13T01:42:15.164-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceUtils: ==============================================================
[2024-09-13T01:42:15.164-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-13T01:42:15.164-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceUtils: ==============================================================
[2024-09-13T01:42:15.164-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkContext: Submitted application: arrow-spark
[2024-09-13T01:42:15.191-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 30720, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-13T01:42:15.201-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceProfile: Limiting resource is cpu
[2024-09-13T01:42:15.201-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-13T01:42:15.284-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SecurityManager: Changing view acls to: gabzarp
[2024-09-13T01:42:15.284-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SecurityManager: Changing modify acls to: gabzarp
[2024-09-13T01:42:15.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SecurityManager: Changing view acls groups to:
[2024-09-13T01:42:15.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SecurityManager: Changing modify acls groups to:
[2024-09-13T01:42:15.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: gabzarp; groups with view permissions: EMPTY; users with modify permissions: gabzarp; groups with modify permissions: EMPTY
[2024-09-13T01:42:15.569-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO Utils: Successfully started service 'sparkDriver' on port 38615.
[2024-09-13T01:42:15.612-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkEnv: Registering MapOutputTracker
[2024-09-13T01:42:15.649-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-13T01:42:15.671-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-13T01:42:15.671-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-13T01:42:15.675-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-13T01:42:15.711-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-232b197d-a10b-4b41-8d01-d1a509362c34
[2024-09-13T01:42:15.726-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-13T01:42:15.745-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-13T01:42:15.903-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-13T01:42:15.964-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-09-13T01:42:15.975-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:15 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2024-09-13T01:42:16.014-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added JAR file:///home/gabzarp/.ivy2/jars/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar at spark://10.255.255.254:38615/jars/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar with timestamp 1726202535131
[2024-09-13T01:42:16.014-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added JAR file:///home/gabzarp/.ivy2/jars/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar at spark://10.255.255.254:38615/jars/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar with timestamp 1726202535131
[2024-09-13T01:42:16.014-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added JAR file:///home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-sync-4.0.5.jar at spark://10.255.255.254:38615/jars/org.mongodb_mongodb-driver-sync-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.014-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added JAR file:///home/gabzarp/.ivy2/jars/org.mongodb_bson-4.0.5.jar at spark://10.255.255.254:38615/jars/org.mongodb_bson-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.014-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added JAR file:///home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-core-4.0.5.jar at spark://10.255.255.254:38615/jars/org.mongodb_mongodb-driver-core-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.017-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added file file:///home/gabzarp/.ivy2/jars/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar at spark://10.255.255.254:38615/files/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar with timestamp 1726202535131
[2024-09-13T01:42:16.019-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Copying /home/gabzarp/.ivy2/jars/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar to /tmp/spark-b0d4bb7b-e607-4a65-879d-66cb675b49e2/userFiles-1073a31e-c62c-4195-84c8-ac56d650adc9/org.mongodb.spark_mongo-spark-connector_2.12-3.0.0.jar
[2024-09-13T01:42:16.037-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added file file:///home/gabzarp/.ivy2/jars/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar at spark://10.255.255.254:38615/files/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar with timestamp 1726202535131
[2024-09-13T01:42:16.038-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Copying /home/gabzarp/.ivy2/jars/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar to /tmp/spark-b0d4bb7b-e607-4a65-879d-66cb675b49e2/userFiles-1073a31e-c62c-4195-84c8-ac56d650adc9/com.microsoft.sqlserver_mssql-jdbc-8.4.1.jre8.jar
[2024-09-13T01:42:16.051-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added file file:///home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-sync-4.0.5.jar at spark://10.255.255.254:38615/files/org.mongodb_mongodb-driver-sync-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.051-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Copying /home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-sync-4.0.5.jar to /tmp/spark-b0d4bb7b-e607-4a65-879d-66cb675b49e2/userFiles-1073a31e-c62c-4195-84c8-ac56d650adc9/org.mongodb_mongodb-driver-sync-4.0.5.jar
[2024-09-13T01:42:16.056-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added file file:///home/gabzarp/.ivy2/jars/org.mongodb_bson-4.0.5.jar at spark://10.255.255.254:38615/files/org.mongodb_bson-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.057-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Copying /home/gabzarp/.ivy2/jars/org.mongodb_bson-4.0.5.jar to /tmp/spark-b0d4bb7b-e607-4a65-879d-66cb675b49e2/userFiles-1073a31e-c62c-4195-84c8-ac56d650adc9/org.mongodb_bson-4.0.5.jar
[2024-09-13T01:42:16.066-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO SparkContext: Added file file:///home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-core-4.0.5.jar at spark://10.255.255.254:38615/files/org.mongodb_mongodb-driver-core-4.0.5.jar with timestamp 1726202535131
[2024-09-13T01:42:16.067-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Copying /home/gabzarp/.ivy2/jars/org.mongodb_mongodb-driver-core-4.0.5.jar to /tmp/spark-b0d4bb7b-e607-4a65-879d-66cb675b49e2/userFiles-1073a31e-c62c-4195-84c8-ac56d650adc9/org.mongodb_mongodb-driver-core-4.0.5.jar
[2024-09-13T01:42:16.161-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://127.0.0.1:7077...
[2024-09-13T01:42:16.202-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO TransportClientFactory: Successfully created connection to /127.0.0.1:7077 after 26 ms (0 ms spent in bootstraps)
[2024-09-13T01:42:16.343-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240913014216-0000
[2024-09-13T01:42:16.355-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46383.
[2024-09-13T01:42:16.356-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO NettyBlockTransferService: Server created on 10.255.255.254:46383
[2024-09-13T01:42:16.358-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-13T01:42:16.365-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.255.255.254, 46383, None)
[2024-09-13T01:42:16.368-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO BlockManagerMasterEndpoint: Registering block manager 10.255.255.254:46383 with 434.4 MiB RAM, BlockManagerId(driver, 10.255.255.254, 46383, None)
[2024-09-13T01:42:16.370-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.255.255.254, 46383, None)
[2024-09-13T01:42:16.373-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.255.255.254, 46383, None)
[2024-09-13T01:42:16.622-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:16 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-09-13T01:42:17.280-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:17 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-13T01:42:17.282-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:17 INFO SharedState: Warehouse path is 'file:/home/gabzarp/airflow/spark-warehouse'.
[2024-09-13T01:42:20.057-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO CodeGenerator: Code generated in 194.229192 ms
[2024-09-13T01:42:20.087-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO SparkContext: Starting job: showString at NativeMethodAccessorImpl.java:0
[2024-09-13T01:42:20.101-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Got job 0 (showString at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-09-13T01:42:20.102-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Final stage: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0)
[2024-09-13T01:42:20.102-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Parents of final stage: List()
[2024-09-13T01:42:20.106-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Missing parents: List()
[2024-09-13T01:42:20.109-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-09-13T01:42:20.220-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 12.8 KiB, free 434.4 MiB)
[2024-09-13T01:42:20.250-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.8 KiB, free 434.4 MiB)
[2024-09-13T01:42:20.253-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.255.255.254:46383 (size: 6.8 KiB, free: 434.4 MiB)
[2024-09-13T01:42:20.256-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-09-13T01:42:20.271-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-09-13T01:42:20.272-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:20 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-09-13T01:42:35.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:35 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-09-13T01:42:50.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:42:50 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-09-13T01:43:05.284-0300] {spark_submit.py:579} INFO - 24/09/13 01:43:05 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-09-13T01:43:20.286-0300] {spark_submit.py:579} INFO - 24/09/13 01:43:20 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-09-13T01:43:35.285-0300] {spark_submit.py:579} INFO - 24/09/13 01:43:35 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-09-13T01:43:36.976-0300] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-09-13T01:43:36.977-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-13T01:43:36.979-0300] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 84537. PIDs of all processes in the group: [84540, 84635, 84537]
[2024-09-13T01:43:36.979-0300] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 84537
[2024-09-13T01:43:36.979-0300] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-13T01:43:36.980-0300] {spark_submit.py:705} INFO - Sending kill signal to spark-submit
[2024-09-13T01:43:36.984-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 493, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 542, in _process_spark_submit_log
    for line in itr:
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-09-13T01:43:36.990-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=elt_documento_pagar_spark, run_id=manual__2024-09-13T04:41:43.125671+00:00, execution_date=20240913T044143, start_date=20240913T044211, end_date=20240913T044336
[2024-09-13T01:43:36.995-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T01:43:36.996-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 77 for task elt_documento_pagar_spark ((sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: UPDATE dag_run SET queued_at=?, execution_date=?, start_date=?, state=?, run_id=?, data_interval_start=?, data_interval_end=?, last_scheduling_decision=?, updated_at=? WHERE dag_run.id = ?]
[parameters: ('2024-09-13 04:41:43.134713', '2024-09-13 04:41:43.125671', '2024-09-13 04:42:09.865160', 'running', 'manual__2024-09-13T04:41:43.125671+00:00', '2024-09-13 04:41:43.125671', '2024-09-13 04:41:43.125671', '2024-09-13 04:42:09.882070', '2024-09-13 04:42:09.893306', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 84537)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 493, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 542, in _process_spark_submit_log
    for line in itr:
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 327, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3427, in handle_failure
    _handle_failure(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1243, in _handle_failure
    TaskInstance.save_to_db(failure_context["ti"], session)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3399, in save_to_db
    session.flush()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: UPDATE dag_run SET queued_at=?, execution_date=?, start_date=?, state=?, run_id=?, data_interval_start=?, data_interval_end=?, last_scheduling_decision=?, updated_at=? WHERE dag_run.id = ?]
[parameters: ('2024-09-13 04:41:43.134713', '2024-09-13 04:41:43.125671', '2024-09-13 04:42:09.865160', 'running', 'manual__2024-09-13T04:41:43.125671+00:00', '2024-09-13 04:41:43.125671', '2024-09-13 04:41:43.125671', '2024-09-13 04:42:09.882070', '2024-09-13 04:42:09.893306', 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-09-13T01:43:37.033-0300] {process_utils.py:80} INFO - Process psutil.Process(pid=84540, status='terminated', started='01:42:10') (84540) terminated with exit code None
[2024-09-13T01:43:37.033-0300] {process_utils.py:80} INFO - Process psutil.Process(pid=84635, status='terminated', started='01:42:13') (84635) terminated with exit code None
[2024-09-13T01:43:37.033-0300] {process_utils.py:80} INFO - Process psutil.Process(pid=84537, status='terminated', exitcode=1, started='01:42:10') (84537) terminated with exit code 1
